In [59]:
import pandas as pd
import geopandas as gpd
import folium
import numpy as np
from geopy.geocoders import Nominatim
import seaborn as sns
from datetime import date
from shapely.geometry import Point

In [60]:
df12=pd.read_csv('dnrpa-robos-recuperos-autos-201912.csv')
df11=pd.read_csv('dnrpa-robos-recuperos-autos-201911.csv')
df10=pd.read_csv('dnrpa-robos-recuperos-autos-201910.csv')
df9=pd.read_csv('dnrpa-robos-recuperos-autos-201909.csv')
df8=pd.read_csv('dnrpa-robos-recuperos-autos-201908.csv')
df7=pd.read_csv('dnrpa-robos-recuperos-autos-201907.csv')
df6=pd.read_csv('dnrpa-robos-recuperos-autos-201906.csv')
df5=pd.read_csv('dnrpa-robos-recuperos-autos-201905.csv')
df4=pd.read_csv('dnrpa-robos-recuperos-autos-201904.csv')
df3=pd.read_csv('dnrpa-robos-recuperos-autos-201903.csv')
df2=pd.read_csv('dnrpa-robos-recuperos-autos-201902.csv')
df1=pd.read_csv('dnrpa-robos-recuperos-autos-201901.csv')

In [61]:
df=df1

In [62]:
df=df.append(df2)
df=df.append(df3)
df=df.append(df4)
df=df.append(df5)
df=df.append(df6)
df=df.append(df7)
df=df.append(df8)
df=df.append(df9)
df=df.append(df10)
df=df.append(df11)
df=df.append(df12)

//anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:6692: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)

### Limpieza

In [63]:
df.drop(columns='registro_seccional_codigo', inplace=True)
df.drop(columns='automotor_tipo_codigo', inplace=True)
df.drop(columns='automotor_marca_codigo', inplace=True)
df.drop(columns='automotor_modelo_codigo', inplace=True)
df.drop(columns='automotor_uso_codigo', inplace=True)
df.drop(columns='titular_domicilio_provincia_id', inplace=True)
df.drop(columns='titular_pais_nacimiento_id', inplace=True)
df.drop(columns='titular_domicilio_provincia_indec_id', inplace=True)
df.drop(columns='titular_pais_nacimiento_indec_id', inplace=True)

In [64]:
df['tramite_tipo']=df['tramite_tipo'].str.title()
df['registro_seccional_descripcion']=df['registro_seccional_descripcion'].str.title()
df['automotor_tipo_descripcion']=df['automotor_tipo_descripcion'].str.title()
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].str.title()
df['automotor_modelo_descripcion']=df['automotor_modelo_descripcion'].str.title()
df['titular_domicilio_localidad']=df['titular_domicilio_localidad'].str.title()
df['titular_domicilio_provincia']=df['titular_domicilio_provincia'].str.title()
df['titular_pais_nacimiento']=df['titular_pais_nacimiento'].str.title()

In [65]:
df['tramite_fecha'] = pd.to_datetime(df['tramite_fecha'])
df['fecha_inscripcion_inicial'] = pd.to_datetime(df['fecha_inscripcion_inicial'])

In [66]:
df['tramite_tipo']=df['tramite_tipo'].replace('Denuncia De Robo O Hurto',
                                              'Denuncia De Robo O Hurto / Retencion Indebida')

In [67]:
df['dia_semana'] = df['tramite_fecha'].dt.dayofweek

In [102]:
df['dia_semana']=df['dia_semana'].replace(0,'Lunes')
df['dia_semana']=df['dia_semana'].replace(1,'Martes')
df['dia_semana']=df['dia_semana'].replace(2,'Miércoles')
df['dia_semana']=df['dia_semana'].replace(3,'Jueves')
df['dia_semana']=df['dia_semana'].replace(4,'Viernes')
df['dia_semana']=df['dia_semana'].replace(5,'Sábado')
df['dia_semana']=df['dia_semana'].replace(6,'Domingo')

In [103]:
df['edad']=2020-df['titular_anio_nacimiento']

In [104]:
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('-058-Hyundai','Hyundai')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('Vokkswagen','Volkswagen')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('B M W','Bmw')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('-112-Renault','Renault')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('Rastrojero Diesel','Rastrojero')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('Reanult','Renault')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('Ranault','Renault')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('-047- Ford','Ford')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('-112- Renault','Renault')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('044 Fiat','Fiat')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('Ford F-100','Ford')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('Jeep Estanciera','Jeep')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('M. Benz','Mercedes Benz')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('A.F.F.','Aff')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('Mercedes-Benz','Mercedes Benz')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('Volskwagen','Volkswagen')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('-044-Fiat','Fiat')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('Vw','Volkswagen')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('Ford F-100 Xlt','Ford')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('Peugeot 504 Srd','Peugeot')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('Peugeot 505 Diesel','Peugeot')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('Peugeot 306 Xrd','Peugeot')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('Peuget','Peugeot')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('Fiat3','Fiat')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('Fiat 619','Fiat')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('Fiat 147 Spazio Tr','Fiat')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('Fiat (044)','Fiat')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('Gmc Chevrolet','Chevrolet')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('Gmc Chevette','Chevrolet')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('Renault (112)','Renault')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('Renault 18 Txe','Renault')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('Fiar','Fiat')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('Ega098Volkswagen','Volkswagen')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('Mecedes Benz','Mercedes Benz')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('M.Benz','Mercedes Benz')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('Maruti',"Suzuki")
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('Nakai','Porsche')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('Kia Motors','Kia')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('Nissan Diesel','Nissan')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('No Posee','Sin Marca')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('Comar','Chevrolet')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('Mercedez Benz','Mercedes Benz')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('Suzuki Carry','Suzuki')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('Citroën','Citroen')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('Aro','Auto Romania')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('Alfa Romero','Alfa Romeo')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('Volkswagn','Volkswagen')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('Volkswgaen','Volkswagen')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('Volkwagen','Volkswagen')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('Chevroelt','Chevrolet')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('Suzuki Swift Sedan Nlx','Suzuki')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('Chrysler Dodge','Dodge')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('Chrysler-Dodge','Dodge')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('Suzuki Swift Sedan Glx','Suzuki')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('Suzuki Swift Gti','Suzuki')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('Prati-Fruehauf','Fruehauf')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('Cherolet','Chevrolet')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('Gmc Chevette','Chevrolet')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('-130- Toyota','Toyota')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('.Peugeot','Peugeot')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('.Toyota','Toyota')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('127 Suzuki','Suzuki')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('19 - Ford','Ford')
df['automotor_marca_descripcion']=df['automotor_marca_descripcion'].replace('-102-Nissan','Nissan')

In [105]:
df["automotor_modelo_descripcion"].replace({'Gol1.9Sd':'Gol 1.9 Sd',
                                            'Gol 1.0 L Mi Plus':'Gol 1.0L Mi Plus',
                                            'Gol 1.Ol Mi Plus 001':'Gol 1.0L Mi Plus',
                                            'Gol 011':'Gol','Gol Mi 001':'Gol Mi',
                                            'Golgli':'Gol Gli',
                                            'Freelander 2.0 Td4 -5 Puertas':'Freelander 2.0 Td4 5 Puertas',
                                            'Ac-Año 2012':'Ac',
                                            'St- Año 2008':'St',
                                            'St - Año 2009':'St',
                                            'St-Año 2004':'St',
                                            'Sc- Año 2011':'Sc',
                                            'Santamo/2000':'Santamo',
                                            'Santamo/1999':'Santamo',
                                            'S.A.D.T. 25 Tt.  3 E  /1998':'S.A.D.T. 25 Tt  3 E','Accord Cb354Nm/Kbjf':'Accord Cb354',
                                            'Accord Ex/1996':'Accord Ex',
                                            'Accord Ex/95':'Accord Ex','Accord Ex V6 - 2004':'Accord Ex V6',
                                            'Accord  Ex':'Accord Ex',
                                            'Golf 2.O':'Golf 2.0',
                                            'Golf Gl 1.8 Mi /1998':'Golf Gl 1.8 Mi',
                                            'Golf 1.4L Tsi Bluemotion Technol':'Golf 1.4L Tsi Bluemotion Technology',
                                            'Golf 1.6 - 2001':'Golf 1.6',
                                            'Golf Gl 1.8 Mi/1999.-':'Golf Gl 1.8 Mi',
                                            'Golf Gl 1.8 Mi/99':'Golf Gl 1.8 Mi',
                                            'Golf1.6':'Golf 1.6','Golf 1.6 2004':'Golf 1.6',
                                            'Golf Gti /2007':'Golf Gti',
                                            'Golf 1.4L Tsi Bluemotion Techno':'Golf 1.4L Tsi Bluemotion Technology',
                                            'Golf Gtd/1998':'Golf Gtd',
                                            'Gol 1.9 Sd 5P      01B':'Gol 1.9 Sd 5P',
                                            'Gol 1.6 01B':'Gol 1.6',
                                            'Gol 1.0 Mi Plus 011':'Gol 1.0 Mi Plus',
                                            'Gol 1.9 Sd (0281) 01A':'Gol 1.9 Sd',
                                            'Gol 1.9 Sd 5P  (0212) 01A':'Gol 1.9 Sd 5P',
                                            'Gol 1.9 Sd (0280) 001':'Gol 1.9 Sd',
                                            'Gol 1.9 Sd 5P 011':'Gol 1.9 Sd 5P',
                                            'Gol 1.9 Sd    01A':'Gol 1.9 Sd',
                                            'Gol 1.9 Sd 5P 01B':'Gol 1.9 Sd 5P',
                                            'Gol 1.9 Sd (0280) 203':'Gol 1.9 Sd',
                                            'Gol 1 Ol Mi Plus':'Gol 1.0L Mi Plus',
                                            'Gol 1.9 Sd 5P (0212)01A':'Gol 1.9 Sd 5P',
                                            'Gol 1.6 (0260) 212':'Gol 1.6',
                                            'Gol 1.9 Sd 5P  (0211)  213':'Gol 1.9 Sd 5P',
                                            'Gol 1.0L Mi Plus 011':'Gol 1.0L Mi Plus',
                                            'Gol 1.6 (0260) 202':'Gol 1.6',
                                            'Gol 1.9 Sd 5P (0211)011':'Gol 1.9 Sd 5P',
                                            'Gol 1.9 Sd 5P (0211)011':'Gol 1.9 Sd 5P',
                                            'Gol 1.6 (0260) 20A':'Gol 1.6',
                                            'Gol 1.OL Mi Plus':'Gol 1.0L Mi Plus',
                                            'Gol 1.OL Mi Plus 001':'Gol 1.0L Mi Plus',
                                            'Gol 1.9 Sd 012':'Gol 1.9 Sd',
                                            'Gol 1.9 Sd/2001':'Gol 1.9 Sd',
                                            'Gol 1.9 Sd  01A':'Gol 1.9 Sd',
                                            'Gol 1.6 011':'Gol 1.6',
                                            'Gol 1.Ol Mi Plus':'Gol 1.0L Mi Plus',
                                            'Gol 1.9 Sd (0211) 213':'Gol 1.9 Sd',
                                            'Gol 1.9 Sd 01A':'Gol 1.9 Sd',
                                            'Gol 1.0 (0250) 011':'Gol 1.0',
                                            'Gol 1.9 Sd 01B':'Gol 1.9 Sd','Gol 1.9 Sd      (0281)     21A':'Gol 1.9 Sd',
                                            'Gol 1.6 5P (0132) 21A':'Gol 1.6 5P',
                                            'Gol 1.6 (0260) 011':'Gol 1.6',
                                            'Gol 1.9 Sd 5P (0211) 213':'Gol 1.9 Sd 5P',
                                            'Gol 1.6 5P (0132) 012':'Gol 1.6 5P',
                                            'Gol 1.6 5P  (0182) 011':'Gol 1.6 5P',
                                            'Gol 1.6 (0270) 01A':'Gol 1.6',
                                            'Gol 1.9 Sd 5P (0212)  20A':'Gol 1.9 Sd 5P',
                                            'Gol 1.6 5P 00B':'Gol 1.6 5P',
                                            'Gol 1.9 Sd 011':'Gol 1.9 Sd',
                                            'Gol 1.6 5P 01B':'Gol 1.6 5P',
                                            'Gol 1.9 Sd (0281) 21B':'Gol 1.9 Sd',
                                            'Gol 1.6 012':'Gol 1.6',
                                            'Gol 1.6 (0270)  012':'Gol 1.6','Gol 1.6 5P  (0132) 01A':'Gol 1.6 5P',
                                            'Gol 1.9 Sd (0280) 011':'Gol 1.9 Sd','Gol 1.0L Mi Plus 001':'Gol 1.0L Mi Plus',
                                            'Gol 1.9 - 2000':'Gol 1.9',
                                            'Gol 1.9 Sd 5P (0212)01A/2001.-':'Gol 1.9 Sd 5P',
                                            'Gol 1.9 Sd   011':'Gol 1.9 Sd',
                                            'Gol 1.9 Sd  (0281) 20A':'Gol 1.9 Sd',
                                            'Gol 1.9 Sd  (0280) 001':'Gol 1.9 Sd',
                                            'Gol 1.9Sd':'Gol 1.9 Sd',
                                            'Gol 1.9 Sd (0280)  001':'Gol 1.9 Sd',
                                            'Gol 1.9 Sd  011':'Gol 1.9 Sd',
                                            'Gol 1.6   012':'Gol 1.6',
                                            'Gol Plus 1.6Mi':'Gol Plus 1.6 Mi',
                                            'Gol Plus 1.6D':'Gol Plus 1.6 D',
                                            'Gol  Country 1.6':'Gol Country 1.6',
                                            'Gol  Cl':'Gol Cl',
                                            'Gol 1.0 L Mi Plus 001':'Gol 1.0L Mi Plus',
                                            'Gol 1.0     (0250) 011':'Gol 1.0',
                                            'Gol 1.0L-Mi Plus':'Gol 1.0L Mi Plus',
                                            'Gol 1.0 L Mi Plus':'Gol 1.0L Mi Plus',
                                            'Gol 1.0L Mi Plus   001':'Gol 1.0L Mi Plus',
                                            'Gol 1.0 L Mi Plus':'Gol 1.0L Mi Plus',
                                            'Gol 1.0  (0250)  001':'Gol 1.0',
                                            'Gol 1.0 L Mi Plus   001':'Gol 1.0 L Mi Plus',
                                            'Gol 1.0L Mi Plus/99.':'Gol 1.0L Mi Plus',
                                            'Gol Mi  001':'Gol Mi',
                                            'Gol Mi    001':'Gol Mi',
                                            'Gol 1.6 /2007':'Gol 1.6',
                                            'Gol 1.6/2003':'Gol 1.6',
                                            'Gol 1.6/2006':'Gol 1.6',
                                            'Gol 1.6 -':'Gol 1.6',
                                            'Gol 1.6 - 2004':'Gol 1.6',
                                            'Gol 1.6              011':'Gol 1.6',
                                            'Gol 1.6/2004':'Gol 1.6',
                                            'Gol 1.6/2005':'Gol 1.6',
                                            'Gol 1.6 /2005.-':'Gol 1.6',
                                            'Gol Trend 1.6/2010':'Gol Trend 1.6',
                                            'Gol Trend 1.6 /2009':'Gol Trend 1.6',
                                            'Gol Country 1.9Sd':'Gol Country 1.9 Sd',
                                            'Gol Cuntry 1.6':'Gol Country 1.6',
                                            'Gol Country 1.6Mi':'Gol Country 1.6 Mi',
                                            'Gol Cli Año 1996':'Gol Cli',
                                            'Gol Cl / 1995':'Gol Cl',
                                            'Gol Country  1.6/2005':'Gol Country  1.6',
                                            'Vw Gol Cl':'Gol Cl',
                                            'Gol Gl /1994':'Gol Gl',
                                            'Gol Gl 1.6 Mi/1999':'Gol Gl 1.6',
                                            'Gol Gl 1.8/2006':'Gol Gl 1.8','Gol Gld/1996':'Gol Gld',
                                            'Gol Gld/1997':'Gol Gld',
                                            'Gol Gl/1992':'Gol Gl',
                                            'Gol Gl/1995':'Gol Gl',
                                            'Gol Gl 1.6 D/1998':'Gol Gl 1.6 D',
                                            'Gol Gl.':'Gol Gl',
                                            'Gol Gl 1.6D':'Gol Gl 1.6 D',
                                            'Gol Gli  1.6':'Gol Gli 1.6',
                                            'Gol Gld.':'Gol Gld',
                                            'Vw Gol Gl':'Gol Gl',
                                            'Gol Gl 1.9Sd':'Gol Gl 1.9 Sd',
                                            'Vw Gol Gl 1.8':'Gol Gl 1.8',
                                            'Gol Gl   /1996':'Gol Gl',
                                            'Gol Gl/93':'Gol Gl',
                                            'Gol Gl 1.6D /1999':'Gol Gl 1.6 D',
                                            'Gol Gld  1997':'Gol Gld',
                                            'Gol Gl 1.6Mi':'Gol Gl 1.6 Mi',
                                            'Gol Gli 1.8.':'Gol Gli 1.8',
                                            'Vw Gol Gli':'Gol Gli',
                                            'Gol Gl 1,6 D':'Gol Gl 1.6 D',
                                            'Gol Gl 1.6D  /1998':'Gol Gl 1.6 D',
                                            'Gol Gli/97':'Gol Gli',
                                            'Gol Gl 1,6 Mi':'Gol Gl 1.6 Mi',
                                            'Gol Gli /1997.-':'Gol Gli',
                                            'Gol Gl.I':'Gol Gli',
                                            'Gol Gl /92.':'Gol Gl',
                                            'Gol Gl 1.6D-1999':'Gol Gl 1.6 D',
                                            'Gol Gli 1997':'Gol Gli'},inplace=True)

In [106]:
df["automotor_modelo_descripcion"].replace({'145 Ts Gt 1.8 16 V':'145 Ts Gt 1.8 16V',
                                            'Srv-2011':'Srv',
                                            'Renault 19 Rn Inyec Bic':'Renault 19 Rn Inyec. (Bic)',
                                            'Renault 19 Rn Inyec.Bic':'Renault 19 Rn Inyec. (Bic)',
                                            'Renault 19 Rn Inyec.Bic':'Renault 19 Rn Inyec. (Bic)',
                                            'Renault 19 Rn Inyec Bic.':'Renault 19 Rn Inyec. (Bic)',
                                            'Renault 19 Rn Inyec.(Bic)':'Renault 19 Rn Inyec. (Bic)',
                                            'Renault 19 Rn Inyec (Bic)':'Renault 19 Rn Inyec. (Bic)',
                                            'Renault 19 Rn Inyec.Bic':'Renault 19 Rn Inyec. (Bic)',
                                            'Renault 19 Rn Inyec Bic':'Renault 19 Rn Inyec. (Bic)'},inplace=True)

In [107]:
df['automotor_modelo_descripcion'].replace({'Renault 19 Rn Inyec.(Tri)':'Renault 19 Rn Inyec. (Tri)',
                                            'Renault 19 Rn Inyec.Tri':'Renault 19 Rn Inyec. (Tri)',
                                            'Renault 19 Rn Inyeccion.(Tri)':'Renault 19 Rn Inyec. (Tri)',
                                            'Renault 19 Rn Inyec (Tri)':'Renault 19 Rn Inyec. (Tri)',},inplace=True)

In [108]:
df['automotor_modelo_descripcion'].replace({'Renault 19 Rt Tric. Iny':'Renault 19 Rt Tric. Iny.',
                                            'Renault 19 Rt Tric.Iny.':'Renault 19 Rt Tric. Iny.',
                                            'Renault 19 Rt Tric Abc':'Renault 19 Rt Tric. Abc',
                                            'Renault 19 Rt Tric.Abc':'Renault 19 Rt Tric. Abc',
                                            'Renault 19 Rt Bic Abc':'Renault 19 Rt Bic.Abc',
                                            'Renault 19 Rt Bicuerpo':'Renault 19 Rt Bic.'},inplace=True)

In [109]:
df['automotor_modelo_descripcion'].replace({'Caravan Se / 1999':'Caravan Se',
                                            'Elantra  1.8 Gls':'Elantra 1.8 Gls',
                                            '-081-Atos Gls  1999':'Atos Gls',
                                            'Grand Cherokee Limited Dieselw':'Grand Cherokee Limited Diesel W',
                                            'Grand Cherokee Limited Quadra Drive':'Grand Cherokee Lim. Qua. Dr.',
                                            'Gr.Cherokee Lim.Diesel Qua.Dr.':'Grand Cherokee Lim. Diesel Qua.Dr.',
                                            'Grand Cherokee Limited/1996':'Grand Cherokee Limited',
                                            'Gr.Cherokee Lim.Qua.Dr.':'Grand Cherokee Lim. Qua. Dr.',
                                            'Gr. Cherokee Lim. Qua Dr.':'Grand Cherokee Lim. Qua. Dr.',
                                            'Grand Cherokee Linited Td':'Grand Cherokee Limited Td',
                                            '530I':'530 I',
                                            '528I':'528 I',
                                            'X5 3.0D Año 2006':'X5 3.0D',
                                            '323I':'323 I',
                                            '320D':'320 D',
                                            '325I':'325 I',
                                            '120I':'120 I',
                                            '330I':'330 I',
                                            '318Tds Compact':'318 Tds Compact',
                                            '323 F Bc9C Lck Glx':'323F Bc9C Lck Glx',
                                            'Inca 1.9 Sd 99A':'Inca 1.9 Sd',
                                            'Inca 1.9D':'Inca 1.9 D',
                                            'Inca 1.9 Sd 991':'Inca 1.9 Sd',
                                            'Cordoba 1.9 Sdi 01A':'Cordoba 1.9 Sdi',
                                            'Cordoba 1.9 Sdi 011':'Cordoba 1.9 Sdi',
                                            'Cordoba 1.9 Tdi 021':'Cordoba 1.9 Tdi',
                                            'Cordoba 1.9 Tdi Sxe 1999':'Cordoba 1.9 Tdi Sxe',
                                            'Cordoba 1.9 Tdi 032':'Cordoba 1.9 Tdi',
                                            'Cordoba 1.6 Mi 01A':'Cordoba 1.6 Mi',
                                            'Cordoba 1.6 Mi 011':'Cordoba 1.6 Mi',
                                            'Cordoba 1.6 Mi  01B':'Cordoba 1.6 Mi',
                                            'Trf54H-00 C/A':'Tfr54H-00 C/A',
                                            'Tfs69Hdei /98':'Tfs69Hdei',
                                            'Renault 19 Re D Aa.Direc.':'Renault 19 Re D Aa. Direc',
                                            'Renault 19 Re D Aa.Direc':'Renault 19 Re D Aa. Direc',
                                            'Renault 19 Re A.A.':'Renault 19 Re Aa',
                                            'Renault 19Re':'Renault 19 Re'},inplace=True)

In [110]:
df['automotor_modelo_descripcion'].replace({'Suran 60A':'Suran',
                                            'Suran 1.6L 5D 717':'Suran 1.6L 5D',
                                            'Suran 1.6L 5D 21B':'Suran 1.6L 5D',
                                            'Suran 1.6L 5D 21A':'Suran 1.6L 5D',
                                            'Suran 1.6L 5D    21A':'Suran 1.6L 5D',
                                            'Suran 1.6 5D 823':'Suran 1.6 5D',
                                            'Suran 1.6L 5D  11A':'Suran 1.6L 5D',
                                            'Suran 60D':'Suran',
                                            'Suran Cross 1.6L 5 Door 061':'Suran Cross 1.6L 5D',
                                            'Suran 1.6L 5P 814':'Suran 1.6L 5P',
                                            'Suran 1.6L 5D   21A':'Suran 1.6L 5D',
                                            'Suran 90A':'Suran',
                                            'Suran 1.6L 5D 21C':'Suran 1.6L 5D',
                                            'Suran 1.6L 5D 11A':'Suran 1.6L 5D',
                                            'Suran 60B':'Suran',
                                            'Suran 1.6L 5D 870':'Suran 1.6L 5D',
                                            'Suran 1.6L 5D      21C':'Suran 1.6L 5D',
                                            'Suran Sdi 90A':'Suran Sdi',
                                            'Suran 1.6 5D 212':'Suran 1.6 5D',
                                            'Fox1.6':'Fox 1.6',
                                            'Fox 1,6/2.005':'Fox 1.6',
                                            'Fox 1.6 5P 71C':'Fox 1.6 5P',
                                            'Fox 1.6/2005':'Fox 1.6',
                                            'Fox 1.6/2010':'Fox 1.6',
                                            'Fox 1.6  /2006':'Fox 1.6',
                                            'Fox  1.6 5P 70A':'Fox  1.6 5P',
                                            'Fox 1.6 5P  70C':'Fox 1.6 5P',
                                            'Fox 1.6 5P 70C':'Fox 1.6 5P',
                                            'Fox 1.6 5P 70A':'Fox 1.6 5P',
                                            'Fox 1.6 /2005':'Fox 1.6',
                                            'Fox 1.6 5P 71A':'Fox 1.6 5P',
                                            'Bora 1.8 T':'Bora 1.8T',
                                            'Renault 19 Injection C /Aa':'Renault 19 Injection C/Aa',
                                            'Renault 19 Rn Inyec Bic 97':'Renault 19 Rn Inyec. (Bic)',
                                            'Renault 19 Rn (Bic) 1994':'Renault 19 Rn (Bic)',
                                            'Renault 19 Rn -Bic-':'Renault 19 Rn (Bic)',
                                            'Renault 19 Rn Iny.(Bic)':'Renault 19 Rn Inyec. (Bic)',
                                            'Renault 19 Rn Bic':'Renault 19 Rn (Bic)',
                                            'Renault 19 Rn Diesel Tri':'Renault 19 Rn Inyec. (Bic)',
                                            'Renault 19 Rn Bic.':'Renault 19 Rn (Bic)',
                                            'Renault 19 Rn( Bic).':'Renault 19 Rn (Bic)',
                                            'Renault 19 Rn (Bic.)':'Renault 19 Rn (Bic)',
                                            'Renault 19 Rn(Bic)':'Renault 19 Rn (Bic)'},inplace=True)

In [111]:
dg=df.copy()

In [112]:
dg['registro_seccional_descripcion']=dg['registro_seccional_descripcion'].str.replace('0','')
dg['registro_seccional_descripcion']=dg['registro_seccional_descripcion'].str.replace('1','')
dg['registro_seccional_descripcion']=dg['registro_seccional_descripcion'].str.replace('2','')
dg['registro_seccional_descripcion']=dg['registro_seccional_descripcion'].str.replace('3','')
dg['registro_seccional_descripcion']=dg['registro_seccional_descripcion'].str.replace('4','')
dg['registro_seccional_descripcion']=dg['registro_seccional_descripcion'].str.replace('5','')
dg['registro_seccional_descripcion']=dg['registro_seccional_descripcion'].str.replace('6','')
dg['registro_seccional_descripcion']=dg['registro_seccional_descripcion'].str.replace('7','')
dg['registro_seccional_descripcion']=dg['registro_seccional_descripcion'].str.replace('8','')
dg['registro_seccional_descripcion']=dg['registro_seccional_descripcion'].str.replace('9','')
dg['registro_seccional_descripcion']=dg['registro_seccional_descripcion'].str.replace('Nº','')
dg['registro_seccional_descripcion']=dg['registro_seccional_descripcion'].str.replace('N°','')

In [113]:
rc=df[df['registro_seccional_descripcion'].str.contains('Capital Federal')==True]['registro_seccional_descripcion']

In [114]:
dg.loc[(dg['registro_seccional_descripcion'].str.contains('Capital Federal')==True),'registro_seccional_descripcion']=rc

In [115]:
dg['automotor_tipo_descripcion']=df['automotor_tipo_descripcion'].str.replace('Ptas','Puertas')

In [116]:
anio=pd.DatetimeIndex(dg[dg['automotor_anio_modelo']==20]['fecha_inscripcion_inicial']).year

In [117]:
dg.loc[(dg['automotor_anio_modelo']==20),'automotor_anio_modelo']=anio

In [118]:
#dg.to_csv('robos-recuperos-autos-2019.csv')

### ¿Cuál es el porcentaje de denuncias de robo en relación al género?

In [119]:
df_D=dg[dg['tramite_tipo']=='Denuncia De Robo O Hurto / Retencion Indebida']

In [120]:
df_D_pF=df_D[df_D['titular_tipo_persona']=='Física']

In [121]:
femenino=len(df_D_pF[df_D_pF['titular_genero']=='Femenino'])
masculino=len(df_D_pF[df_D_pF['titular_genero']=='Masculino'])
no_identificado=len(df_D_pF[df_D_pF['titular_genero']=='No identificado'])
total=femenino+masculino+no_identificado

In [122]:
femenino/total

0.2522105756280377

In [123]:
masculino/total

0.5627744920067927

In [124]:
no_identificado/total

0.18501493236516953

### ¿Es más probable que un auto nuevo sea robado?

In [125]:
autos_nuevos=len(df_D[df_D['automotor_anio_modelo']>=2017])
total=len(df_D[df_D['automotor_anio_modelo'].isnull()==False])

In [126]:
autos_nuevos/total

0.06313924918576082

In [127]:
df_D.groupby('automotor_anio_modelo').count().sort_values(by='tramite_tipo',ascending=False).head()

,automotor_marca_descripcion,automotor_modelo_descripcion,automotor_origen,automotor_tipo_descripcion,automotor_uso_descripcion,fecha_inscripcion_inicial,registro_seccional_descripcion,registro_seccional_provincia,titular_anio_nacimiento,titular_domicilio_localidad,...,titular_domicilio_provincia_indec_id,titular_genero,titular_pais_nacimiento,titular_pais_nacimiento_indec_id,titular_porcentaje_titularidad,titular_tipo_persona,tramite_fecha,tramite_tipo,dia_semana,edad
automotor_anio_modelo,,,,,,,,,,,,,,,,,,,,,
2011.0,1914,1914,1914,1914,1914,1914,1914,1914,1914,1909,...,501,1914,1914,484,1914,1914,1914,1914,1914,1914
2008.0,1785,1785,1785,1785,1785,1785,1785,1785,1785,1783,...,420,1785,1785,405,1785,1785,1785,1785,1785,1785
2007.0,1777,1777,1777,1777,1777,1777,1777,1777,1777,1773,...,435,1777,1777,419,1777,1777,1777,1777,1777,1777
2012.0,1752,1752,1752,1752,1752,1752,1752,1752,1752,1749,...,374,1752,1752,361,1752,1752,1752,1752,1752,1752
2013.0,1731,1731,1731,1731,1730,1731,1731,1731,1731,1727,...,412,1731,1731,392,1731,1731,1731,1731,1731,1731

In [128]:
autos_2011=len(df_D[df_D['automotor_anio_modelo']==2011])

In [129]:
autos_2011/total

0.054682589566310495

In [130]:
autos_2011_a_2013=len(df_D[df_D['automotor_anio_modelo'].between(2011,2013,inclusive=True)])

In [131]:
autos_2011_a_2013/total

0.15419118907491

### ¿Qué día de la semana hay más trámites?

In [132]:
dg.groupby('dia_semana').count().sort_values(by='tramite_tipo',ascending=False)

,automotor_anio_modelo,automotor_marca_descripcion,automotor_modelo_descripcion,automotor_origen,automotor_tipo_descripcion,automotor_uso_descripcion,fecha_inscripcion_inicial,registro_seccional_descripcion,registro_seccional_provincia,titular_anio_nacimiento,...,titular_domicilio_provincia,titular_domicilio_provincia_indec_id,titular_genero,titular_pais_nacimiento,titular_pais_nacimiento_indec_id,titular_porcentaje_titularidad,titular_tipo_persona,tramite_fecha,tramite_tipo,edad
dia_semana,,,,,,,,,,,,,,,,,,,,,
Miércoles,7607,7637,7637,7637,7637,7637,7637,7637,7637,7633,...,7637,2053,7637,7637,1908,7637,7637,7637,7637,7633
Jueves,7360,7387,7387,7387,7387,7387,7387,7387,7387,7385,...,7387,1957,7387,7387,1790,7387,7387,7387,7387,7385
Martes,7270,7304,7304,7304,7304,7304,7304,7304,7304,7302,...,7304,1704,7304,7304,1594,7304,7304,7304,7304,7302
Lunes,7235,7258,7258,7258,7258,7257,7258,7258,7258,7256,...,7258,1724,7258,7258,1603,7258,7258,7258,7258,7256
Viernes,7203,7249,7249,7249,7249,7249,7248,7249,7249,7248,...,7249,1781,7249,7249,1666,7249,7249,7249,7249,7248
Sábado,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1

### ¿Cuál es la provincia con más denuncias de robos? ¿Y el partido dentro de la provincia?

In [133]:
df_D.groupby('registro_seccional_provincia').count().sort_values(by='tramite_tipo',ascending=False).head()

,automotor_anio_modelo,automotor_marca_descripcion,automotor_modelo_descripcion,automotor_origen,automotor_tipo_descripcion,automotor_uso_descripcion,fecha_inscripcion_inicial,registro_seccional_descripcion,titular_anio_nacimiento,titular_domicilio_localidad,...,titular_domicilio_provincia_indec_id,titular_genero,titular_pais_nacimiento,titular_pais_nacimiento_indec_id,titular_porcentaje_titularidad,titular_tipo_persona,tramite_fecha,tramite_tipo,dia_semana,edad
registro_seccional_provincia,,,,,,,,,,,,,,,,,,,,,
Buenos Aires,23639,23745,23745,23745,23745,23744,23744,23745,23745,23708,...,5945,23745,23745,5763,23745,23745,23745,23745,23745,23745
Ciudad Autónoma de Bs.As.,5222,5252,5252,5252,5252,5252,5252,5252,5252,5252,...,1398,5252,5252,1218,5252,5252,5252,5252,5252,5252
Córdoba,2455,2459,2459,2459,2459,2459,2459,2459,2459,2459,...,573,2459,2459,551,2459,2459,2459,2459,2459,2459
Mendoza,1449,1459,1459,1459,1459,1459,1459,1459,1459,1445,...,392,1459,1459,373,1459,1459,1459,1459,1459,1459
Santa Fe,1321,1324,1324,1324,1324,1324,1324,1324,1324,1324,...,284,1324,1324,269,1324,1324,1324,1324,1324,1324

In [134]:
df_D_BsAs=df_D[df_D['registro_seccional_provincia']=='Buenos Aires']

In [135]:
df_D_BsAs.groupby('registro_seccional_descripcion').count().sort_values(by='tramite_tipo',ascending=False).head()

,automotor_anio_modelo,automotor_marca_descripcion,automotor_modelo_descripcion,automotor_origen,automotor_tipo_descripcion,automotor_uso_descripcion,fecha_inscripcion_inicial,registro_seccional_provincia,titular_anio_nacimiento,titular_domicilio_localidad,...,titular_domicilio_provincia_indec_id,titular_genero,titular_pais_nacimiento,titular_pais_nacimiento_indec_id,titular_porcentaje_titularidad,titular_tipo_persona,tramite_fecha,tramite_tipo,dia_semana,edad
registro_seccional_descripcion,,,,,,,,,,,,,,,,,,,,,
La Matanza,3743,3751,3751,3751,3751,3750,3751,3751,3751,3747,...,899,3751,3751,883,3751,3751,3751,3751,3751,3751
Lomas De Zamora,1515,1524,1524,1524,1524,1524,1524,1524,1524,1524,...,383,1524,1524,375,1524,1524,1524,1524,1524,1524
Adrogue,1150,1158,1158,1158,1158,1158,1158,1158,1158,1158,...,312,1158,1158,310,1158,1158,1158,1158,1158,1158
Lanus,1154,1158,1158,1158,1158,1158,1157,1158,1158,1157,...,263,1158,1158,255,1158,1158,1158,1158,1158,1158
La Plata,1079,1106,1106,1106,1106,1106,1106,1106,1106,1106,...,247,1106,1106,235,1106,1106,1106,1106,1106,1106

### ¿Coince la provincia con más denuncias de robo con la que posee más comunicaciones de recupero? ¿Y el partido?

In [136]:
df_R=dg[dg['tramite_tipo']=='Comunicación De Recupero']

In [137]:
df_R.groupby('registro_seccional_provincia').count().sort_values(by='tramite_tipo',ascending=False).head()

,automotor_anio_modelo,automotor_marca_descripcion,automotor_modelo_descripcion,automotor_origen,automotor_tipo_descripcion,automotor_uso_descripcion,fecha_inscripcion_inicial,registro_seccional_descripcion,titular_anio_nacimiento,titular_domicilio_localidad,...,titular_domicilio_provincia_indec_id,titular_genero,titular_pais_nacimiento,titular_pais_nacimiento_indec_id,titular_porcentaje_titularidad,titular_tipo_persona,tramite_fecha,tramite_tipo,dia_semana,edad
registro_seccional_provincia,,,,,,,,,,,,,,,,,,,,,
Buenos Aires,757,758,758,758,758,758,758,758,756,757,...,197,758,758,102,758,758,758,758,758,756
Ciudad Autónoma de Bs.As.,623,624,624,624,624,624,624,624,617,624,...,131,624,624,30,624,624,624,624,624,617
Córdoba,129,130,130,130,130,130,130,130,130,130,...,26,130,130,20,130,130,130,130,130,130
Santa Fe,66,66,66,66,66,66,66,66,64,66,...,13,66,66,2,66,66,66,66,66,64
Mendoza,31,31,31,31,31,31,31,31,31,31,...,9,31,31,9,31,31,31,31,31,31

In [138]:
df_R_BsAs=df_R[df_R['registro_seccional_provincia']=='Buenos Aires']

In [139]:
df_R_BsAs.groupby('registro_seccional_descripcion').count().sort_values(by='tramite_tipo',ascending=False).head()

,automotor_anio_modelo,automotor_marca_descripcion,automotor_modelo_descripcion,automotor_origen,automotor_tipo_descripcion,automotor_uso_descripcion,fecha_inscripcion_inicial,registro_seccional_provincia,titular_anio_nacimiento,titular_domicilio_localidad,...,titular_domicilio_provincia_indec_id,titular_genero,titular_pais_nacimiento,titular_pais_nacimiento_indec_id,titular_porcentaje_titularidad,titular_tipo_persona,tramite_fecha,tramite_tipo,dia_semana,edad
registro_seccional_descripcion,,,,,,,,,,,,,,,,,,,,,
La Plata,323,323,323,323,323,323,323,323,323,323,...,94,323,323,7,323,323,323,323,323,323
La Matanza,52,52,52,52,52,52,52,52,52,52,...,16,52,52,15,52,52,52,52,52,52
Olivos,35,35,35,35,35,35,35,35,35,35,...,6,35,35,0,35,35,35,35,35,35
Adrogue,30,30,30,30,30,30,30,30,30,30,...,10,30,30,10,30,30,30,30,30,30
Lanus,29,29,29,29,29,29,29,29,29,29,...,7,29,29,7,29,29,29,29,29,29

### ¿Cuál es el tiempo promedio entre denuncia de robo y comunicación de recupero?

In [140]:
df_D2=df_D.copy()
df_R2=df_R.copy()
df_R2['tramite_fecha2']=df_R2['tramite_fecha']
df_R2['tramite_tipo2']=df_R2['tramite_tipo']
df_R2.drop(columns=['tramite_tipo','tramite_fecha','edad','dia_semana'],inplace=True)
df_D2.drop(columns=['edad','dia_semana'],inplace=True)

In [172]:
df_DR=pd.merge(df_D2,df_R2,on=['automotor_anio_modelo',
                              'automotor_marca_descripcion',
                              'automotor_modelo_descripcion',
                              'automotor_origen',
                              'automotor_uso_descripcion',
                              'fecha_inscripcion_inicial',
                              'registro_seccional_descripcion',
                              'registro_seccional_provincia',
                              'titular_anio_nacimiento',
                              'titular_domicilio_provincia',
                              'titular_genero',
                              'titular_pais_nacimiento',
                              'titular_tipo_persona'])

In [174]:
df_DR['delta_tiempo'] = df_DR['tramite_fecha2']-df_DR['tramite_fecha']

In [175]:
df_DR.drop(df_DR[df_DR['delta_tiempo']<np.timedelta64(0, 'D')].index, inplace=True)

In [176]:
df_DR['delta_tiempo'].describe()

count                         351
mean     100 days 06:05:07.692307
std       68 days 20:55:32.016063
min               0 days 00:00:00
25%              51 days 12:00:00
50%              81 days 00:00:00
75%             136 days 12:00:00
max             339 days 00:00:00
Name: delta_tiempo, dtype: object